language: node_js
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.12.3
  - export PATH="$HOME/.yarn/bin:$PATH"
stages:
  - lint
  - name: deploy
    if: branch = master
jobs:
  include:
    - stage: lint
      script: yarn lint
    - stage: deploy
      script: yarn api:deploy