language: node_js
node_js:
  - "node"
stages:
  - lint
  - name: deploy
    if: branch = master
jobs:
  include:
    - stage: lint
      script: yarn lint
    - stage: deploy
      script: yarn api:deploy